"""empty message

Revision ID: 070804cc40b7
Revises: d4c10d9995e6
Create Date: 2026-01-23 15:52:25.884534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070804cc40b7'
down_revision: Union[str, Sequence[str], None] = 'd4c10d9995e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 먼저 product 테이블에 컬럼이 있는지 확인하고 없으면 만듭니다.
    # (이미 이전 파일에서 만들었을 수도 있으니 안전하게 작성합니다)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('product')]
    
    if 'region_id' not in columns:
        op.add_column('product', sa.Column('region_id', sa.String(length=36), nullable=False))

    # 2. 인덱스 생성
    try:
        op.create_index(op.f('ix_product_region_id'), 'product', ['region_id'], unique=False)
    except Exception:
        pass # 이미 있으면 넘어감

    # 3. 외래 키 설정 (이게 지금 에러가 났던 부분!)
    op.create_foreign_key(
        'fk_product_region_id',
        'product', 
        'region', 
        ['region_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    
    # 4. 나머지 코드
    op.create_index(op.f('ix_user_product_product_id'), 'user_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_product_user_id'), 'user_product', ['user_id'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_user_id'), table_name='user_product')
    op.drop_index(op.f('ix_user_product_product_id'), table_name='user_product')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_region_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_column('product', 'region_id')
    # ### end Alembic commands ###
