"""empty message

Revision ID: 070804cc40b7
Revises: d4c10d9995e6
Create Date: 2026-01-23 15:52:25.884534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070804cc40b7'
down_revision: Union[str, Sequence[str], None] = 'd4c10d9995e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_region_id'), 'product', ['region_id'], unique=False)
    op.create_foreign_key(None, 'product', 'region', ['region_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_product_product_id'), 'user_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_product_user_id'), 'user_product', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_user_id'), table_name='user_product')
    op.drop_index(op.f('ix_user_product_product_id'), table_name='user_product')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_region_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_column('product', 'region_id')
    # ### end Alembic commands ###
