"""empty message

Revision ID: 089d6ff409b1
Revises: d42c88516574
Create Date: 2026-01-24 16:47:45.793361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from carrot.app.region.models import MySQLGeometry

# revision identifiers, used by Alembic.
revision: str = '089d6ff409b1'
down_revision: Union[str, Sequence[str], None] = 'd42c88516574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # --- [1] Product 테이블 관련 수정 ---
    product_cols = [c['name'] for c in inspector.get_columns('product')]
    
    # region_id 컬럼이 없을 때만 추가
    if 'region_id' not in product_cols:
        op.add_column('product', sa.Column('region_id', sa.String(length=36), nullable=False))
    
    # 인덱스 및 외래키는 이미 있을 수 있으니 에러 발생 시 무시하도록 처리하거나 체크
    try:
        op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    except: pass
    
    try:
        op.create_index(op.f('ix_product_region_id'), 'product', ['region_id'], unique=False)
    except: pass
    
    try:
        op.create_foreign_key('fk_product_region_id_new', 'product', 'region', ['region_id'], ['id'], ondelete='CASCADE')
    except: pass

    # --- [2] Region 테이블 관련 수정 ---
    region_cols = [c['name'] for c in inspector.get_columns('region')]
    
    if 'sido' not in region_cols:
        op.add_column('region', sa.Column('sido', sa.String(length=20), nullable=False))
    if 'sigugun' not in region_cols:
        op.add_column('region', sa.Column('sigugun', sa.String(length=20), nullable=False))
    if 'dong' not in region_cols:
        op.add_column('region', sa.Column('dong', sa.String(length=20), nullable=False))
    if 'geom' not in region_cols:
        op.add_column('region', sa.Column('geom', MySQLGeometry(), nullable=False))
        
    op.alter_column('region', 'full_name', existing_type=mysql.VARCHAR(length=100), nullable=False)
    
    # 인덱스 정리
    try: op.drop_index(op.f('ix_region_name'), table_name='region')
    except: pass
    
    try: op.create_index('idx_region_geom', 'region', ['geom'], unique=False, mysql_prefix='SPATIAL')
    except: pass
    
    try: op.create_index(op.f('ix_region_sido'), 'region', ['sido'], unique=False)
    except: pass
    
    try: op.create_index(op.f('ix_region_sigugun'), 'region', ['sigugun'], unique=False)
    except: pass
    
    try: op.create_unique_constraint('uix_region_sido_sigugun_dong', 'region', ['sido', 'sigugun', 'dong'])
    except: pass
    
    if 'name' in region_cols:
        op.drop_column('region', 'name')

    # --- [3] UserProduct 테이블 관련 수정 ---
    try: op.create_index(op.f('ix_user_product_product_id'), 'user_product', ['product_id'], unique=False)
    except: pass
    try: op.create_index(op.f('ix_user_product_user_id'), 'user_product', ['user_id'], unique=False)
    except: pass
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_user_id'), table_name='user_product')
    op.drop_index(op.f('ix_user_product_product_id'), table_name='user_product')
    op.add_column('region', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint('uix_region_sido_sigugun_dong', 'region', type_='unique')
    op.drop_index(op.f('ix_region_sigugun'), table_name='region')
    op.drop_index(op.f('ix_region_sido'), table_name='region')
    op.drop_index('idx_region_geom', table_name='region', mysql_prefix='SPATIAL')
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.alter_column('region', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('region', 'geom')
    op.drop_column('region', 'dong')
    op.drop_column('region', 'sigugun')
    op.drop_column('region', 'sido')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_region_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_column('product', 'region_id')
    # ### end Alembic commands ###
