"""empty message

Revision ID: 4acbbaffde7f
Revises: 02113ebfba74
Create Date: 2026-01-29 00:16:01.242143

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4acbbaffde7f'
down_revision: Union[str, Sequence[str], None] = '02113ebfba74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)

    # 1. product_image 테이블 삭제 로직 (존재할 때만)
    if insp.has_table("product_image"):
        # 인덱스 존재 여부 확인 후 삭제
        existing_indices = [idx['name'] for idx in insp.get_indexes("product_image")]
        if "ix_product_image_id" in existing_indices:
            op.drop_index("ix_product_image_id", table_name="product_image")
        op.drop_table("product_image")

    # 2. uq_auction_product_id 유니크 제약 조건 추가 (존재하지 않을 때만)
    # auction 테이블의 모든 제약 조건 이름을 가져옵니다.
    existing_constraints = [c['name'] for c in insp.get_unique_constraints("auction")]
    if "uq_auction_product_id" not in existing_constraints:
        op.create_unique_constraint(
            "uq_auction_product_id",
            "auction",
            ["product_id"],
        )
    else:
        print("Constraint 'uq_auction_product_id' already exists, skipping.")

    # 3. image_ids 컬럼 추가 (존재하지 않을 때만)
    existing_columns = [c['name'] for c in insp.get_columns('product')]
    if 'image_ids' not in existing_columns:
        op.add_column('product', sa.Column('image_ids', sa.JSON(), nullable=False))
    else:
        print("Column 'image_ids' already exists, skipping.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_ids')
    op.drop_index(op.f('ix_auction_product_id'), table_name='auction')
    op.create_index(op.f('ix_auction_product_id'), 'auction', ['product_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    # ### end Alembic commands ###
