"""empty message

Revision ID: 4acbbaffde7f
Revises: 02113ebfba74
Create Date: 2026-01-29 00:16:01.242143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4acbbaffde7f'
down_revision: Union[str, Sequence[str], None] = '02113ebfba74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_auction_product_id'), table_name='auction')
    op.create_index(op.f('ix_auction_product_id'), 'auction', ['product_id'], unique=True)
    op.add_column('product', sa.Column('image_ids', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_ids')
    op.drop_index(op.f('ix_auction_product_id'), table_name='auction')
    op.create_index(op.f('ix_auction_product_id'), 'auction', ['product_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    # ### end Alembic commands ###
