"""empty message

Revision ID: 4ade29ccdc03
Revises: 60d78f000fc5
Create Date: 2026-01-12 14:44:19.425466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ade29ccdc03'
down_revision: Union[str, Sequence[str], None] = '60d78f000fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.String(length=36), nullable=False))
    op.alter_column('product', 'title',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('product', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.create_index(op.f('ix_product_owner_id'), 'product', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'product', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_owner_id'), table_name='product')
    op.alter_column('product', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('product', 'title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###
