"""empty message

Revision ID: 4af7d6ed3bd8
Revises: a039904b38fe
Create Date: 2026-01-12 18:13:39.332220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af7d6ed3bd8'
down_revision: Union[str, Sequence[str], None] = 'a039904b38fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAW', 'TRANSFER', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('receive_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['receive_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    # ### end Alembic commands ###
