"""empty message

Revision ID: 60d78f000fc5
Revises: b6c95fdcb71e
Create Date: 2026-01-05 02:31:22.725427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60d78f000fc5'
down_revision: Union[str, Sequence[str], None] = 'b6c95fdcb71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_account',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_social_account_id'), table_name='social_account')
    op.drop_column('social_account', 'id')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('social_account', sa.Column('id', mysql.VARCHAR(length=36), nullable=False))
    op.create_index(op.f('ix_social_account_id'), 'social_account', ['id'], unique=False)
    op.drop_table('local_account')
    # ### end Alembic commands ###
