"""empty message

Revision ID: 88d754858e1d
Revises: d42c88516574
Create Date: 2026-01-26 14:31:06.782185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d754858e1d'
down_revision: Union[str, Sequence[str], None] = 'd42c88516574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    op.add_column('product', sa.Column('image_ids', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_product_image_ids'), 'product', ['image_ids'], unique=False)
    op.create_index(op.f('ix_product_owner_id'), 'product', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_owner_id'), table_name='product')
    op.drop_index(op.f('ix_product_image_ids'), table_name='product')
    op.drop_column('product', 'image_ids')
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    # ### end Alembic commands ###
