"""empty message

Revision ID: af5801142c80
Revises: fb5444b402e9
Create Date: 2026-01-04 19:23:50.278736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af5801142c80'
down_revision: Union[str, Sequence[str], None] = 'fb5444b402e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'region_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'region_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
