"""empty message

Revision ID: d4e67e3246b5
Revises: cdfdeca872a6
Create Date: 2026-01-27 19:05:15.151133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e67e3246b5'
down_revision: Union[str, Sequence[str], None] = 'cdfdeca872a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 테이블 생성은 그대로 둡니다 (만약 이것도 이미 있다면 에러가 날 테니, 
    # 그럴 땐 이 부분도 주석 처리하거나 if문으로 감싸야 합니다.)
    op.create_table('product_image',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)

    # 2. [문제의 구간] 이미 컬럼이 존재하므로 이 한 줄을 주석 처리합니다.
    # op.add_column('product', sa.Column('image_ids', sa.JSON(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_ids')
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    # ### end Alembic commands ###
