"""Add auction table

Revision ID: d8b900239f14
Revises: dd590e290f3e
Create Date: 2026-01-27 19:15:03.619400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b900239f14'
down_revision: Union[str, Sequence[str], None] = 'dd590e290f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('starting_price', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_id'), 'auction', ['id'], unique=False)
    op.create_index(op.f('ix_auction_product_id'), 'auction', ['product_id'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('bidder_id', sa.String(length=36), nullable=False),
    sa.Column('bid_price', sa.Integer(), nullable=False),
    sa.Column('bid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_auction_id'), 'bid', ['auction_id'], unique=False)
    op.create_index(op.f('ix_bid_bidder_id'), 'bid', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_bidder_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_auction_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_auction_product_id'), table_name='auction')
    op.drop_index(op.f('ix_auction_id'), table_name='auction')
    op.drop_table('auction')
    # ### end Alembic commands ###
