"""empty message

Revision ID: e3a938fcd78d
Revises: 089d6ff409b1
Create Date: 2026-01-24 21:28:15.282969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3a938fcd78d'
down_revision: Union[str, Sequence[str], None] = '089d6ff409b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat_room',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_room_id'), 'group_chat_room', ['id'], unique=False)
    op.create_table('group_chat_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['group_chat_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_message', sa.Column('group_room_id', sa.String(length=36), nullable=True))
    op.alter_column('chat_message', 'room_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_chat_message_group_room_id'), 'chat_message', ['group_room_id'], unique=False)
    op.create_foreign_key(None, 'chat_message', 'group_chat_room', ['group_room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_index(op.f('ix_chat_message_group_room_id'), table_name='chat_message')
    op.alter_column('chat_message', 'room_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('chat_message', 'group_room_id')
    op.drop_table('group_chat_member')
    op.drop_index(op.f('ix_group_chat_room_id'), table_name='group_chat_room')
    op.drop_table('group_chat_room')
    # ### end Alembic commands ###
