"""empty message

Revision ID: fb5444b402e9
Revises: 4c9ffeff6c6a
Create Date: 2026-01-04 19:21:12.624367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb5444b402e9'
down_revision: Union[str, Sequence[str], None] = '4c9ffeff6c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
